import { set, toggle } from '@/utils/vuex'
let config = {
  prodUrl: 'http://212.227.193.201/api/v1/',
  devUrl: 'http://212.227.193.201/api/v1/',
  createPath: 'producer/create',
  loginPath: 'producer/login',
  logoutPath: 'producer/logout',
  fetchPath: 'producer/profile/fetch',
  fetchMenuListPath: 'producer/menu/items/list',
  createMenuItemPath: 'producer/menu/item/create',
  updateMenuItemPath: 'producer/menu/item/update',
  fetchLunchListPath: 'producer/offers/lunch/list',
  createLunchtemPath: 'producer/offers/lunch/create',
  fetchLunchtemPath: 'producer/offers/lunch/fetch/',
  updateLunchItemPath: 'producer/offers/lunch/update',
  fetchSpecialOffersPath: 'producer/offers/special/list',
  fetchSpecialOfferPath: 'producer/offer/special/fetch/',
  createSpecialOfferPath: 'producer/offers/special/create',
  updateSpecialOfferPath: 'producer/offers/special/update',
  createCategoryPath: 'producer/menu/category/create',
  listCateoriesPath: 'producer/menu/categories/list',
  deleteCategoryPath: 'producer/menu/category/delete',
  getAvailableMainItemsPath: 'producer/menu/items/names/fetch',
  getAvailableLunchOnlyItemsPath: 'producer/menu/items/lunch/fetch',
  deleteMainItemPath: 'producer/menu/item/delete',
  deleteLunchItemPath: 'producer/offers/special/delete',
  deleteSpiecialItemPath: 'producer/offers/lunch/delete',
  addImage: 'producer/menu/{type}/image/add',
  basePath: './',
  prodPost: '?prod=true',
  prodGet: '?prod=true'
}

export default {
  namespaced: true,
  state: {
    apiUrl: config.devUrl,
    url: config.devUrl,
    basePath: config.basePath,
    prodPost: config.prodPost,
    prodGet: config.prodGet,
    createPath: config.createPath,
    loginPath: config.loginPath,
    logoutPath: config.logoutPath,
    fetchPath: config.fetchPath,
    createCategoryPath: config.createCategoryPath,
    listCateoriesPath: config.listCateoriesPath,
    deleteCategoryPath: config.deleteCategoryPath,
    createMenuItemPath: config.createMenuItemPath,
    updateMenuItemPath: config.updateMenuItemPath,
    fetchMenuListPath: config.fetchMenuListPath,
    fetchSpecialOffersPath: config.fetchSpecialOffersPath,
    fetchSpecialOfferPath: config.fetchSpecialOfferPath,
    createSpecialOfferPath: config.createSpecialOfferPath,
    updateSpecialOfferPath: config.updateSpecialOfferPath,
    addImage: config.addImage,
    fetchLunchListPath: config.fetchLunchListPath,
    fetchLunchtemPath: config.fetchLunchtemPath,
    createLunchtemPath: config.createLunchtemPath,
    updateLunchItemPath: config.updateLunchItemPath,
    getAvailableMainItemsPath: config.getAvailableMainItemsPath,
    getAvailableLunchOnlyItemsPath: config.getAvailableLunchOnlyItemsPath,
    deleteMainItemPath: config.deleteMainItemPath,
    deleteLunchItemPath: config.deleteLunchItemPath,
    deleteSpiecialItemPath: config.deleteSpiecialItemPath,
  },
  mutations: {},
  getters: {},
  actions: {}
}
